---
title: "Performance evaluation"
output: html_notebook
---


(Presentar este documento bien, con fecha etc)


```{r}
library("tm")
library("quanteda")
source("auxiliar_functions.R")
```


# Load parameters
```{r}
train.data<-readRDS(file = "train.data.RDS")
predict.word<- readRDS(file = "predict_word.RDS")


```


Fast easy prediction

```{r}

```

#Parameter cost
```{r}

response.time<-system.time(result <- predict.word("Tomorrow I will go to"), gcFirst = TRUE)[1]
training.size<-object.size(train.data)/1024^2 # in MB



```




# Test in validation data

```{r}
  evaluation.dir<-"./clean_data/training/"
  test.size<-100
  corpus.source<-DirSource(evaluation.dir)
  tmcorpus1 <- tm::VCorpus(corpus.source, readerControl = list(reader=readPlain,language = "en"))
  validation.corpus<-corpus(tmcorpus1)
  sentences<-tokens(validation.corpus, remove_url = TRUE,  what = "sentence")

  sampled.sentences<-sample(unlist(sentences),size = test.size)
  sampled.sentences<-tolower(sampled.sentences)
  sampled.sentences<-removePunctuation(sampled.sentences)
  sampled.sentences<-removeNumbers(sampled.sentences)
  sampled.sentences<-stripWhitespace(removeNumbers(sampled.sentences))
  
  #remove sentences with length 1 
  nwords<-function (x)
  {
    words<-unlist(strsplit(x," "))
    length(words)
  }
  
  
  large.sentences<-(sapply(X=sampled.sentences, FUN=nwords) > 2)
  sampled.sentences<-sampled.sentences[large.sentences]
  

  

```


Data frame with results

```{r}
  result<-data.frame(sampled.sentences)
  result$sampled.sentences<-as.character(result$sampled.sentences)
  
  
  get.query<-function (x)
  {
    words<-unlist(strsplit(x," "))
    paste(words[1:length(words)-1],collapse=" ")
  }
  
  get.correct.word<-function (x)
  {
    words<-unlist(strsplit(x," "))
    words[length(words)]
  }
  
  
  
  result$query<-sapply(X=result$sampled.sentences, FUN=get.query)
  result$correct.word<-sapply(X=result$sampled.sentences, FUN=get.correct.word)
  


  
```


Execution 
```{r}
result$prediction<-sapply(X=result$query,FUN = function(x) {predict.word(x)$word})
```



Measures 
```{r}
result$correct<-(result$prediction==result$correct.word)
accuracy<-mean(result$correct)


```

```{r}
print(list(  evaluation.dir=evaluation.dir,  test.size=test.size,response.time=response.time, training.size=training.size,accuracy=accuracy))

```

